### PR TITLE
Merge for core rewrite functionality Update (v0.2.alpha1)

### PR DESCRIPTION
**Pull request by Luna-Klatzer**
# Summary
Merging the two v0.2 development branches since the core rewrite branch is almost finished and the new replacing functionality is almost entirely implemented. 

## Current Changes
- Added proper `closing` and resolved issues with tasks staying alive after run-time 
- Implemented proper Exception and traceback handling
- Updated logging module appropriately with the changes of exception-handling
- Changed Type implementation from storage classes to interface classes, which will only serve the purpose of interacting with the Hiven API and not actual data-storing. For proper data storage, the `ClientCache` was implemented which will store all data in a dictionary, which is more light-weight and faster than Hiven Objects
- Implemented `ClientCache` as a dictionary for storing the client data in a JSON-like format for simpler accessing
   Properties:
      - token (string passed on run())
      - log_ws_output (boolean passed on init)
      - client_user (dict with properties as keys
      - houses (dict with ids as key)
      - users (dict with ids as key)
      - rooms (dict with types as keys):
        ```
        {
                'private': {
                    'single': dict(),
                    'multi': dict()
                },
                'house': dict()
         }
        ```
      - entities: (dict with ids as key)
      - relationships (dict with user ids as key)
      - house_memberships (dict with ids as key)
      - house_ids: (list with ids as values)
      - settings: (dict with properties as keys)
      - read_state: (dict with message ids as keys)
- Added `MultiEventListener` and `SingleEventListener` with `wait_for`, `add_single_listener` and `add_multi_listener` for listening to events additionally to the basic `@client.event()`
  
  Usage Example:
  `wait_for`: Waits for an event and calls a function on receiving the event
  ```py
   ...
  @client.event()
  async def on_ready():
      async def coro():
          print("Message was created")
      # Will wait for the event message_create to be received. 
      # After dispatched, the function will be called, and when finished 
      # the args and kwargs are returned as list and dict
      args, kwargs = await client.wait_for('message_create', coro)
  ```  

  `add_single_listener`/`add_multi_listener`: Will add a listener for an event and call the function either once (single_listener) or every time it is received (multi_listener)
  ```py
  ...
  async def coro():
      print("Message was created")
  add_single_listener('message_create', coro) 
  ...
  ```
- Rewrote the WebSocket Event- and Exception-Handling
- Implemented fastjsonschema validation in the data-classes
- added `format_obj_data(data: dict)` and `validate(data: dict, *args, **kwargs)` to the data-classes for data-validation and object-creation
- Added base `Object` class that is inherited by all module classes and `DataClassObject` for all Data-Classes such as `House` 
- Created a basic parser system that is separated from the WebSocket
- Added pytest for checking functionality and coverage-checks

### CODE REVIEW

**Comment by Nicolas-Klatzer** [comment]
Added with commit b742d647eb0209f6416d0087a8e35655ffbd3d89 HTTP-Exception, cleaned up code and added more type-hinting. Worked on the types as well but class creation and assembly, especially in Message and House with dictionaries of values there will need to be a lot more work to fetch all data from the cache and create the instances correctly

**Review by Nxybi — CHANGES_REQUESTED** [review]
I don't personally think pytest should be pushed to repo/pypi

**Comment by Nicolas-Klatzer** [comment]
> 
> 
> I don't personally think pytest should be pushed to repo/pypi

It shouldn't include it though OwO

**Comment by Nicolas-Klatzer** [comment]
Updated with 9bc1f6fa05ffc2d8925a06eec6ca5e3bdd992551 the Types System:
- Construction of referenced objects such as a house in a member instance will be delayed until the user calls the @property function. This means that the private variables will now serve as cache, which at first will only be a string and then contain the object if the user requests it. (The class will also need an update function to avoid the possibility that the object is updated and the cached object is then outdated. To that there might be an issue if the house is deleted that the user cannot get the house anymore, a security if-statement will then need to be added, so it does not error when the cache does not contain the object)
- Updated type hinting
- Moved construction entirely to the `__init__()` function
- Removed async calls from the construction, so the object only require raw data to be passed

**Comment by Nicolas-Klatzer** [comment]
Added now the checks with 0fd8328b23ca8b72d012e1e7e8b68188de63b752 to avoid that it will return an exception when it is not found

**Review by Luna-Klatzer — COMMENTED** [review]
it's my code, so... good to go

**Review by Luna-Klatzer — COMMENTED** [review]
It's fine

**Pull request merged**
